// Données des 18 régions françaises
const REGIONS = {
  "auvergne-rhone-alpes": {
    name: "Auvergne-Rhône-Alpes",
    type: "metro",
    icon: "⛰️",
    color: "#f4a8a0",
    chef: "Lyon",
    population: "8 092 000",
    superficie: "69 711 km²",
    departements: 12,
    densite: "116 hab/km²",
    devise: "—",
    histoire: "Née en 2016 de la fusion de l'Auvergne et de Rhône-Alpes, cette région est la deuxième plus peuplée de France. Carrefour historique entre le nord et la Méditerranée, elle abrite Lyon, ancienne capitale des Gaules fondée par les Romains en 43 av. J.-C. La région a longtemps été un pôle industriel majeur (soie lyonnaise, métallurgie) et reste un centre économique de premier plan.",
    geo: "Territoire très contrasté : massif des Alpes à l'est (avec le Mont Blanc, point culminant d'Europe occidentale), Massif central à l'ouest, et la vallée du Rhône au centre. Climat montagnard, continental et méditerranéen selon les zones.",
    economie: "Industrie, tourisme alpin, agriculture (élevage, vignobles du Beaujolais), recherche et hautes technologies. Grenoble est un pôle scientifique européen.",
    villes: ["Lyon", "Grenoble", "Saint-Étienne", "Clermont-Ferrand", "Annecy"],
    points: ["Mont Blanc (4 808 m)", "Vieux Lyon (UNESCO)", "Volcans d'Auvergne", "Lac d'Annecy"]
  },
  "bourgogne-franche-comte": {
    name: "Bourgogne-Franche-Comté",
    type: "metro",
    icon: "🍷",
    color: "#c9a0dc",
    chef: "Dijon",
    population: "2 805 000",
    superficie: "47 784 km²",
    departements: 8,
    densite: "59 hab/km²",
    devise: "—",
    histoire: "Fusion en 2016 de la Bourgogne, ancien duché puissant au Moyen Âge rivalisant avec le royaume de France, et de la Franche-Comté, longtemps possession espagnole puis rattachée à la France en 1678 sous Louis XIV. La Bourgogne est mondialement réputée pour ses vins depuis l'époque des moines cisterciens.",
    geo: "Région de plateaux, de collines et de massifs (Morvan, Jura). Climat semi-continental. Nombreux cours d'eau et le célèbre vignoble de la Côte-d'Or.",
    economie: "Viticulture de prestige, agroalimentaire, industrie automobile et microtechnique (Franche-Comté), tourisme œnologique.",
    villes: ["Dijon", "Besançon", "Chalon-sur-Saône", "Nevers", "Auxerre"],
    points: ["Vignobles de Bourgogne (UNESCO)", "Hospices de Beaune", "Citadelle de Besançon", "Parc du Morvan"]
  },
  "bretagne": {
    name: "Bretagne",
    type: "metro",
    icon: "⚓",
    color: "#f9b8d6",
    chef: "Rennes",
    population: "3 373 000",
    superficie: "27 208 km²",
    departements: 4,
    densite: "124 hab/km²",
    devise: "Kentoc'h mervel eget bezañ saotret",
    histoire: "Ancien royaume puis duché indépendant, la Bretagne fut rattachée à la France en 1532. Région à forte identité celtique, elle a conservé sa langue (le breton), ses traditions, sa musique et ses fest-noz. Terre de marins et de pêcheurs, elle est tournée vers l'océan Atlantique.",
    geo: "Vaste péninsule à l'ouest de la France, entourée par la Manche et l'Atlantique. Côtes découpées, caps, et un intérieur de landes et de bocages (l'Argoat). Climat océanique doux et humide.",
    economie: "Agriculture et agroalimentaire (premier producteur français), pêche, tourisme côtier, télécommunications (Rennes).",
    villes: ["Rennes", "Brest", "Quimper", "Lorient", "Saint-Malo"],
    points: ["Mont-Saint-Michel (à la frontière)", "Pointe du Raz", "Côte de Granit Rose", "Carnac et ses mégalithes"]
  },
  "centre-val-de-loire": {
    name: "Centre-Val de Loire",
    type: "metro",
    icon: "🏰",
    color: "#f5e6a0",
    chef: "Orléans",
    population: "2 573 000",
    superficie: "39 151 km²",
    departements: 6,
    densite: "66 hab/km²",
    devise: "—",
    histoire: "Berceau de la Renaissance française, la région du Val de Loire fut le lieu de villégiature des rois de France qui y firent construire de somptueux châteaux. Orléans est célèbre pour Jeanne d'Arc qui y leva le siège anglais en 1429. La région a joué un rôle central dans l'histoire de France.",
    geo: "Traversée par la Loire, plus long fleuve de France. Paysages de plaines fertiles (Beauce), forêts (Sologne) et coteaux viticoles. Climat océanique dégradé.",
    economie: "Agriculture céréalière (la Beauce, grenier de la France), viticulture, tourisme des châteaux, cosmétique et pharmacie.",
    villes: ["Orléans", "Tours", "Bourges", "Blois", "Chartres"],
    points: ["Châteaux de la Loire (Chambord, Chenonceau)", "Cathédrale de Chartres", "Val de Loire (UNESCO)", "Zoo de Beauval"]
  },
  "corse": {
    name: "Corse",
    type: "metro",
    icon: "🏝️",
    color: "#a0d8c0",
    chef: "Ajaccio",
    population: "344 000",
    superficie: "8 680 km²",
    departements: 2,
    densite: "40 hab/km²",
    devise: "—",
    histoire: "Surnommée l'Île de Beauté, la Corse fut génoise pendant des siècles avant d'être cédée à la France en 1768, un an avant la naissance de Napoléon Bonaparte à Ajaccio. L'île possède une forte identité culturelle, sa langue corse et une histoire marquée par les luttes pour l'autonomie.",
    geo: "Île montagneuse de la Méditerranée, la plus montagneuse des îles méditerranéennes (Monte Cinto, 2 706 m). Côtes spectaculaires, maquis odorant et climat méditerranéen.",
    economie: "Tourisme (pilier de l'économie), agriculture (vin, charcuterie, clémentines, miel), artisanat.",
    villes: ["Ajaccio", "Bastia", "Porto-Vecchio", "Corte", "Calvi"],
    points: ["Calanques de Piana (UNESCO)", "Golfe de Porto", "Bonifacio", "Réserve de Scandola"]
  },
  "grand-est": {
    name: "Grand Est",
    type: "metro",
    icon: "🌲",
    color: "#b5d99c",
    chef: "Strasbourg",
    population: "5 556 000",
    superficie: "57 433 km²",
    departements: 10,
    densite: "97 hab/km²",
    devise: "—",
    histoire: "Fusion en 2016 de l'Alsace, la Lorraine et la Champagne-Ardenne. Région frontalière de l'Allemagne, la Belgique, le Luxembourg et la Suisse, son histoire est marquée par les conflits franco-allemands : l'Alsace-Lorraine fut annexée par l'Allemagne de 1871 à 1918. Strasbourg est aujourd'hui une capitale européenne.",
    geo: "De la plaine d'Alsace au massif des Vosges, des coteaux de Champagne aux Ardennes. Climat continental marqué. Traversée par le Rhin, la Moselle et la Marne.",
    economie: "Viticulture (champagne et vins d'Alsace), industrie, institutions européennes (Parlement européen à Strasbourg), commerce transfrontalier.",
    villes: ["Strasbourg", "Reims", "Metz", "Nancy", "Mulhouse"],
    points: ["Cathédrale de Strasbourg", "Route des Vins d'Alsace", "Place Stanislas à Nancy (UNESCO)", "Caves de Champagne"]
  },
  "guadeloupe": {
    name: "Guadeloupe",
    type: "dom",
    icon: "🌺",
    color: "#7ec8e3",
    chef: "Basse-Terre",
    population: "384 000",
    superficie: "1 628 km²",
    departements: 1,
    densite: "236 hab/km²",
    devise: "—",
    histoire: "Archipel des Antilles colonisé par la France au XVIIe siècle, marqué par l'histoire de l'esclavage et des plantations sucrières, aboli définitivement en 1848. Département français depuis 1946, la Guadeloupe mêle cultures africaine, européenne et indienne dans une identité créole vibrante.",
    geo: "Archipel en forme de papillon dans la mer des Caraïbes : Basse-Terre (montagneuse et volcanique avec la Soufrière) et Grande-Terre (plate et calcaire). Climat tropical.",
    economie: "Tourisme, agriculture (canne à sucre, banane, rhum), pêche.",
    villes: ["Basse-Terre", "Pointe-à-Pitre", "Les Abymes", "Le Gosier"],
    points: ["Volcan de la Soufrière", "Plages des Antilles", "Parc national de la Guadeloupe", "Îles des Saintes"]
  },
  "guyane": {
    name: "Guyane",
    type: "dom",
    icon: "🌿",
    color: "#7ec8e3",
    chef: "Cayenne",
    population: "286 000",
    superficie: "83 534 km²",
    departements: 1,
    densite: "3,4 hab/km²",
    devise: "—",
    histoire: "Située en Amérique du Sud, la Guyane fut colonisée au XVIIe siècle. Tristement célèbre pour son bagne (dont l'île du Diable) jusqu'en 1946, elle est devenue département français la même année. Depuis 1968, elle accueille le Centre spatial guyanais à Kourou, port spatial de l'Europe.",
    geo: "Plus vaste région de France, couverte à plus de 90 % par la forêt amazonienne. Climat équatorial chaud et humide. Riche biodiversité.",
    economie: "Activité spatiale (Ariane), exploitation aurifère, pêche, filière bois, biodiversité.",
    villes: ["Cayenne", "Saint-Laurent-du-Maroni", "Kourou", "Matoury"],
    points: ["Centre spatial de Kourou", "Forêt amazonienne", "Îles du Salut", "Réserve des Nouragues"]
  },
  "hauts-de-france": {
    name: "Hauts-de-France",
    type: "metro",
    icon: "🏭",
    color: "#f5d76e",
    chef: "Lille",
    population: "5 998 000",
    superficie: "31 813 km²",
    departements: 5,
    densite: "189 hab/km²",
    devise: "—",
    histoire: "Fusion en 2016 du Nord-Pas-de-Calais et de la Picardie. Région la plus septentrionale de France, ancien cœur industriel (charbon, textile, sidérurgie). Théâtre majeur des deux guerres mondiales, notamment la bataille de la Somme. Terre d'accueil et de solidarité, riche d'un patrimoine minier reconnu.",
    geo: "Plaines et bas plateaux ouverts sur la mer du Nord et la Manche. Climat océanique. Proche de la Belgique et de l'Angleterre (tunnel sous la Manche).",
    economie: "Logistique et commerce, agriculture (betterave, pomme de terre), industrie agroalimentaire et automobile, services.",
    villes: ["Lille", "Amiens", "Roubaix", "Dunkerque", "Calais"],
    points: ["Beffrois (UNESCO)", "Bassin minier (UNESCO)", "Cathédrale d'Amiens", "Baie de Somme"]
  },
  "ile-de-france": {
    name: "Île-de-France",
    type: "metro",
    icon: "🗼",
    color: "#e8a87c",
    chef: "Paris",
    population: "12 271 000",
    superficie: "12 011 km²",
    departements: 8,
    densite: "1 022 hab/km²",
    devise: "—",
    histoire: "Cœur historique et politique de la France, l'Île-de-France s'organise autour de Paris, capitale depuis le Moyen Âge. Berceau du pouvoir royal (Versailles), de la Révolution française et siège des institutions. Région la plus peuplée et la plus riche, c'est le moteur économique du pays.",
    geo: "Région-capitale au centre du Bassin parisien, traversée par la Seine et la Marne. Forte urbanisation autour de Paris, mais aussi forêts et terres agricoles en grande couronne.",
    economie: "Première région économique de France et l'une des premières d'Europe : finance, services, tourisme, recherche, industrie de luxe et technologies.",
    villes: ["Paris", "Boulogne-Billancourt", "Saint-Denis", "Versailles", "Créteil"],
    points: ["Tour Eiffel", "Château de Versailles (UNESCO)", "Louvre", "Disneyland Paris"]
  },
  "la-reunion": {
    name: "La Réunion",
    type: "dom",
    icon: "🌋",
    color: "#7ec8e3",
    chef: "Saint-Denis",
    population: "873 000",
    superficie: "2 512 km²",
    departements: 1,
    densite: "347 hab/km²",
    devise: "—",
    histoire: "Île de l'océan Indien, inhabitée avant sa colonisation française au XVIIe siècle. Son peuplement par des colons, des esclaves africains et malgaches, puis des engagés indiens et chinois, a créé une société métissée unique. Département français depuis 1946.",
    geo: "Île volcanique tropicale, dominée par le Piton des Neiges (3 071 m) et le très actif Piton de la Fournaise. Cirques spectaculaires, forêts et plages. Climat tropical.",
    economie: "Tourisme, agriculture (canne à sucre, fruits tropicaux), services publics, énergie.",
    villes: ["Saint-Denis", "Saint-Paul", "Saint-Pierre", "Le Tampon"],
    points: ["Piton de la Fournaise", "Cirques (UNESCO)", "Plages de l'Hermitage", "Piton des Neiges"]
  },
  "martinique": {
    name: "Martinique",
    type: "dom",
    icon: "🎶",
    color: "#7ec8e3",
    chef: "Fort-de-France",
    population: "350 000",
    superficie: "1 128 km²",
    departements: 1,
    densite: "310 hab/km²",
    devise: "—",
    histoire: "Île des Antilles, surnommée l'« île aux fleurs », colonisée par la France en 1635. Son histoire est marquée par l'esclavage des plantations puis son abolition (1848). En 1902, l'éruption de la montagne Pelée détruisit Saint-Pierre. Département depuis 1946, terre natale d'Aimé Césaire.",
    geo: "Île volcanique de la mer des Caraïbes dominée par la montagne Pelée. Reliefs verdoyants au nord, plaines et plages au sud. Climat tropical.",
    economie: "Tourisme, agriculture (banane, canne à sucre, rhum agricole AOC), pêche.",
    villes: ["Fort-de-France", "Le Lamentin", "Le Robert", "Schœlcher"],
    points: ["Montagne Pelée", "Jardin de Balata", "Les Anses d'Arlet", "Distilleries de rhum"]
  },
  "mayotte": {
    name: "Mayotte",
    type: "dom",
    icon: "🐢",
    color: "#7ec8e3",
    chef: "Mamoudzou",
    population: "320 000",
    superficie: "374 km²",
    departements: 1,
    densite: "856 hab/km²",
    devise: "—",
    histoire: "Île de l'archipel des Comores dans l'océan Indien, Mayotte a choisi par référendum de rester française lors de l'indépendance des Comores en 1975. Elle est devenue le 101e département français en 2011. Territoire à majorité musulmane, c'est le département le plus jeune et l'un des plus pauvres.",
    geo: "Île volcanique entourée de l'un des plus grands lagons fermés du monde, protégé par une barrière de corail. Climat tropical humide.",
    economie: "Services publics, agriculture (ylang-ylang, vanille), pêche, aquaculture.",
    villes: ["Mamoudzou", "Koungou", "Dzaoudzi", "Dembéni"],
    points: ["Lagon de Mayotte", "Îlot de sable blanc", "Mont Choungui", "Récif corallien"]
  },
  "normandie": {
    name: "Normandie",
    type: "metro",
    icon: "🎠",
    color: "#e88b8b",
    chef: "Rouen",
    population: "3 327 000",
    superficie: "29 907 km²",
    departements: 5,
    densite: "111 hab/km²",
    devise: "—",
    histoire: "Ancien duché fondé par les Vikings au Xe siècle, la Normandie a donné Guillaume le Conquérant, roi d'Angleterre en 1066. Région réunifiée en 2016, elle est mondialement connue pour le Débarquement allié du 6 juin 1944 qui amorça la libération de l'Europe. Patrie des impressionnistes (Monet).",
    geo: "Région littorale ouverte sur la Manche, faite de bocages, de falaises (Étretat) et de plaines. Climat océanique doux et humide.",
    economie: "Agriculture (élevage laitier, fromages, cidre), industrie portuaire et automobile, tourisme mémoriel et balnéaire.",
    villes: ["Rouen", "Le Havre", "Caen", "Cherbourg", "Évreux"],
    points: ["Plages du Débarquement", "Mont-Saint-Michel", "Falaises d'Étretat", "Jardins de Monet à Giverny"]
  },
  "nouvelle-aquitaine": {
    name: "Nouvelle-Aquitaine",
    type: "metro",
    icon: "🏄",
    color: "#a8c97f",
    chef: "Bordeaux",
    population: "6 034 000",
    superficie: "84 036 km²",
    departements: 12,
    densite: "72 hab/km²",
    devise: "—",
    histoire: "Plus grande région de France métropolitaine, née en 2016 de la fusion de l'Aquitaine, du Limousin et du Poitou-Charentes. Terre d'Aliénor d'Aquitaine, longtemps disputée entre la France et l'Angleterre durant la guerre de Cent Ans. Bordeaux, port de la lune, prospéra grâce au commerce du vin.",
    geo: "De la côte atlantique (la plus longue plage de sable d'Europe) aux Pyrénées, en passant par les forêts des Landes et les vallées de la Dordogne. Climat océanique.",
    economie: "Viticulture mondialement réputée (Bordeaux, Cognac), aéronautique, agriculture, tourisme balnéaire et thermal.",
    villes: ["Bordeaux", "Limoges", "Poitiers", "Pau", "La Rochelle"],
    points: ["Dune du Pilat", "Vignobles de Bordeaux", "Grottes de Lascaux", "Biarritz et la côte basque"]
  },
  "occitanie": {
    name: "Occitanie",
    type: "metro",
    icon: "☀️",
    color: "#e8956b",
    chef: "Toulouse",
    population: "6 022 000",
    superficie: "72 724 km²",
    departements: 13,
    densite: "83 hab/km²",
    devise: "—",
    histoire: "Fusion en 2016 du Languedoc-Roussillon et de Midi-Pyrénées. Terre de la langue d'oc et de la civilisation occitane, elle fut marquée par la croisade contre les Cathares au XIIIe siècle. Toulouse, la ville rose, est devenue la capitale européenne de l'aéronautique et de l'espace.",
    geo: "Des Pyrénées à la Méditerranée, en passant par les Causses et la vallée de la Garonne. Climat méditerranéen sur le littoral, plus montagnard à l'intérieur.",
    economie: "Aéronautique et spatial (Airbus), agriculture, viticulture, tourisme balnéaire et de montagne.",
    villes: ["Toulouse", "Montpellier", "Nîmes", "Perpignan", "Carcassonne"],
    points: ["Cité de Carcassonne (UNESCO)", "Pont du Gard", "Canal du Midi (UNESCO)", "Cirque de Gavarnie"]
  },
  "pays-de-la-loire": {
    name: "Pays de la Loire",
    type: "metro",
    icon: "🚢",
    color: "#9ec9a8",
    chef: "Nantes",
    population: "3 838 000",
    superficie: "32 082 km²",
    departements: 5,
    densite: "120 hab/km²",
    devise: "—",
    histoire: "Région créée dans les années 1950, à cheval sur d'anciennes provinces (Anjou, Maine, une partie de la Bretagne historique avec Nantes). Nantes fut la ville des ducs de Bretagne puis un grand port marchand, marqué par le commerce triangulaire. Région dynamique tournée vers l'Atlantique.",
    geo: "Région littorale atlantique, traversée par la Loire. Bocages, marais (le Marais poitevin), plages et îles (Noirmoutier, Yeu). Climat océanique doux.",
    economie: "Industrie navale et aéronautique, agriculture et agroalimentaire, tourisme balnéaire, numérique.",
    villes: ["Nantes", "Angers", "Le Mans", "Saint-Nazaire", "La Roche-sur-Yon"],
    points: ["Château des ducs de Bretagne", "Les Machines de l'île à Nantes", "Puy du Fou", "Marais poitevin"]
  },
  "provence-alpes-cote-d-azur": {
    name: "Provence-Alpes-Côte d'Azur",
    type: "metro",
    icon: "🌊",
    color: "#f5c842",
    chef: "Marseille",
    population: "5 098 000",
    superficie: "31 400 km²",
    departements: 6,
    densite: "162 hab/km²",
    devise: "—",
    histoire: "Souvent abrégée PACA, cette région du sud-est fut l'une des premières terres romanisées de la Gaule (la Provincia romaine). Marseille, fondée par les Grecs vers 600 av. J.-C., est la plus ancienne ville de France. La Côte d'Azur devint au XIXe siècle un lieu de villégiature mondain prestigieux.",
    geo: "Des Alpes du Sud à la Méditerranée, paysages de montagnes, de garrigue et de calanques. Climat méditerranéen ensoleillé, balayé par le mistral.",
    economie: "Tourisme (premier pôle touristique après Paris), services, high-tech (Sophia Antipolis), agriculture méditerranéenne (lavande, olives), parfumerie (Grasse).",
    villes: ["Marseille", "Nice", "Toulon", "Aix-en-Provence", "Cannes"],
    points: ["Calanques de Marseille", "Promenade des Anglais à Nice", "Gorges du Verdon", "Palais des Papes à Avignon"]
  }
};

if (typeof module !== "undefined") module.exports = REGIONS;
