// Données des régions de France
const REGIONS_DATA = {
  "auvergne-rhone-alpes": {
    name: "Auvergne-Rhône-Alpes",
    type: "metro",
    icon: "⛰️",
    chef: "Lyon",
    color: "#f4a8a0",
    population: "8 092 598",
    superficie: "69 711 km²",
    departements: 12,
    densite: "116 hab/km²",
    histoire: "Née de la fusion de l'Auvergne et de Rhône-Alpes en 2016, cette région réunit des territoires volcaniques (chaîne des Puys, classée à l'UNESCO) et alpins (Mont Blanc, plus haut sommet d'Europe occidentale). Lyon, sa capitale, fut la capitale des Gaules sous l'Empire romain et reste un haut lieu de la gastronomie et de la soie.",
    points: "Mont Blanc · Volcans d'Auvergne · Vieux Lyon · Stations de ski des Alpes · Gastronomie lyonnaise",
    economie: "Industrie, tourisme de montagne, chimie, agroalimentaire et numérique."
  },
  "bourgogne-franche-comte": {
    name: "Bourgogne-Franche-Comté",
    type: "metro",
    icon: "🍷",
    chef: "Dijon",
    color: "#c9b6e4",
    population: "2 805 580",
    superficie: "47 784 km²",
    departements: 8,
    densite: "59 hab/km²",
    histoire: "Issue de la fusion de la Bourgogne et de la Franche-Comté, la région est mondialement connue pour ses vignobles classés au patrimoine de l'UNESCO. Le duché de Bourgogne fut au Moyen Âge l'un des plus puissants États d'Europe.",
    points: "Vignobles de Bourgogne · Dijon · Abbaye de Cluny · Hospices de Beaune · Jura",
    economie: "Viticulture, agroalimentaire, métallurgie et tourisme œnologique."
  },
  "bretagne": {
    name: "Bretagne",
    type: "metro",
    icon: "⚓",
    chef: "Rennes",
    color: "#f6b8d8",
    population: "3 373 835",
    superficie: "27 208 km²",
    departements: 4,
    densite: "124 hab/km²",
    histoire: "Ancien duché indépendant rattaché à la France en 1532, la Bretagne possède une forte identité culturelle (langue bretonne, musique celtique). Sa côte découpée et ses légendes arthuriennes (forêt de Brocéliande) en font une terre de caractère.",
    points: "Côte de Granit Rose · Mont Saint-Michel (à proximité) · Carnac · Saint-Malo · Festivals celtiques",
    economie: "Agriculture, pêche, agroalimentaire, télécommunications et tourisme."
  },
  "centre-val-de-loire": {
    name: "Centre-Val de Loire",
    type: "metro",
    icon: "🏰",
    chef: "Orléans",
    color: "#f5e6a8",
    population: "2 573 295",
    superficie: "39 151 km²",
    departements: 6,
    densite: "66 hab/km²",
    histoire: "Surnommée le « Jardin de la France », cette région est célèbre pour ses châteaux de la Loire (Chambord, Chenonceau, Amboise), témoins de la Renaissance française. Jeanne d'Arc y libéra Orléans en 1429.",
    points: "Château de Chambord · Chenonceau · Cathédrale de Chartres · Vallée de la Loire (UNESCO)",
    economie: "Agriculture céréalière, viticulture, pharmacie, cosmétique et tourisme."
  },
  "corse": {
    name: "Corse",
    type: "metro",
    icon: "🏝️",
    chef: "Ajaccio",
    color: "#a8e0c8",
    population: "344 679",
    superficie: "8 680 km²",
    departements: 2,
    densite: "40 hab/km²",
    histoire: "L'« Île de Beauté » fut gênoise avant de devenir française en 1768. Napoléon Bonaparte y naquit à Ajaccio en 1769. Collectivité à statut particulier, elle conjugue montagnes, maquis et plages de rêve.",
    points: "Ajaccio (maison de Napoléon) · Calanques de Piana · Bonifacio · GR20 · Réserve de Scandola",
    economie: "Tourisme, agriculture (vin, charcuterie, fromage) et artisanat."
  },
  "grand-est": {
    name: "Grand Est",
    type: "metro",
    icon: "🌲",
    chef: "Strasbourg",
    color: "#bce06a",
    population: "5 562 651",
    superficie: "57 433 km²",
    departements: 10,
    densite: "97 hab/km²",
    histoire: "Fusion de l'Alsace, la Champagne-Ardenne et la Lorraine, le Grand Est est marqué par l'histoire franco-allemande. Strasbourg accueille le Parlement européen. La Champagne y produit le célèbre vin effervescent.",
    points: "Strasbourg (cathédrale, Petite France) · Reims · Route des vins d'Alsace · Champagne",
    economie: "Viticulture (champagne), industrie automobile, métallurgie et institutions européennes."
  },
  "guadeloupe": {
    name: "Guadeloupe",
    type: "dom",
    icon: "🌺",
    chef: "Basse-Terre",
    color: "#ED2939",
    population: "384 239",
    superficie: "1 628 km²",
    departements: 1,
    densite: "236 hab/km²",
    histoire: "Archipel des Antilles françaises en forme de papillon, colonisé au XVIIe siècle. Marquée par l'histoire de l'esclavage et de l'abolition, la Guadeloupe possède une culture créole riche.",
    points: "Plages des Caraïbes · Volcan de la Soufrière · Chutes du Carbet · Îles des Saintes",
    economie: "Tourisme, canne à sucre, banane, rhum et pêche."
  },
  "guyane": {
    name: "Guyane",
    type: "dom",
    icon: "🌿",
    chef: "Cayenne",
    color: "#ED2939",
    population: "286 618",
    superficie: "83 846 km²",
    departements: 1,
    densite: "3,4 hab/km²",
    histoire: "Plus vaste région de France, située en Amérique du Sud et couverte à 95 % par la forêt amazonienne. Elle abrite le Centre Spatial Guyanais de Kourou, base de lancement européenne.",
    points: "Centre Spatial de Kourou · Forêt amazonienne · Îles du Salut · Réserves naturelles",
    economie: "Industrie spatiale, orpaillage, bois et pêche."
  },
  "hauts-de-france": {
    name: "Hauts-de-France",
    type: "metro",
    icon: "🏭",
    chef: "Lille",
    color: "#f5d020",
    population: "5 983 823",
    superficie: "31 813 km²",
    departements: 5,
    densite: "188 hab/km²",
    histoire: "Fusion du Nord-Pas-de-Calais et de la Picardie. Terre minière et industrielle, théâtre de grandes batailles des deux guerres mondiales. Lille en est le cœur dynamique avec son architecture flamande.",
    points: "Vieux Lille · Beffrois (UNESCO) · Baie de Somme · Côte d'Opale · Mémoriaux 14-18",
    economie: "Logistique, agroalimentaire, automobile, textile et commerce."
  },
  "ile-de-france": {
    name: "Île-de-France",
    type: "metro",
    icon: "🗼",
    chef: "Paris",
    color: "#7a8c5a",
    population: "12 271 794",
    superficie: "12 011 km²",
    departements: 8,
    densite: "1 022 hab/km²",
    histoire: "Région capitale autour de Paris, cœur politique, économique et culturel de la France depuis le Moyen Âge. Elle concentre les institutions de l'État, des monuments mondialement connus et la plus forte densité du pays.",
    points: "Tour Eiffel · Louvre · Château de Versailles · Notre-Dame · Disneyland Paris",
    economie: "Finance, services, tourisme, luxe, technologie — première région économique de France."
  },
  "la-reunion": {
    name: "La Réunion",
    type: "dom",
    icon: "🌋",
    chef: "Saint-Denis",
    color: "#ED2939",
    population: "873 102",
    superficie: "2 504 km²",
    departements: 1,
    densite: "349 hab/km²",
    histoire: "Île volcanique de l'océan Indien, peuplée à partir du XVIIe siècle. Sa population métissée (créole, indienne, africaine, chinoise, européenne) en fait un modèle de diversité. Le Piton de la Fournaise est l'un des volcans les plus actifs du monde.",
    points: "Piton de la Fournaise · Cirques de Mafate, Salazie et Cilaos (UNESCO) · Plages · Lagons",
    economie: "Tourisme, canne à sucre, agriculture tropicale et services."
  },
  "martinique": {
    name: "Martinique",
    type: "dom",
    icon: "🎶",
    chef: "Fort-de-France",
    color: "#ED2939",
    population: "364 508",
    superficie: "1 128 km²",
    departements: 1,
    densite: "323 hab/km²",
    histoire: "« Île aux fleurs » des Antilles, terre natale d'Aimé Césaire et de Joséphine de Beauharnais. L'éruption de la montagne Pelée en 1902 détruisit Saint-Pierre. Culture créole et musicale (zouk) vibrante.",
    points: "Montagne Pelée · Plages du sud · Jardin de Balata · Distilleries de rhum · Saint-Pierre",
    economie: "Tourisme, banane, rhum, canne à sucre et pêche."
  },
  "mayotte": {
    name: "Mayotte",
    type: "dom",
    icon: "🐢",
    chef: "Mamoudzou",
    color: "#ED2939",
    population: "310 022",
    superficie: "374 km²",
    departements: 1,
    densite: "829 hab/km²",
    histoire: "Plus jeune département français (2011), situé dans l'archipel des Comores, dans l'océan Indien. Sa population, majoritairement musulmane, possède une culture mahoraise unique. Son lagon est l'un des plus grands du monde.",
    points: "Lagon de Mayotte · Tortues marines · Îlot de sable blanc · Mont Choungui",
    economie: "Pêche, agriculture, ylang-ylang, vanille et aides publiques."
  },
  "normandie": {
    name: "Normandie",
    type: "metro",
    icon: "🎠",
    chef: "Rouen",
    color: "#f4a8a0",
    population: "3 327 077",
    superficie: "29 907 km²",
    departements: 5,
    densite: "111 hab/km²",
    histoire: "Terre des Vikings devenue duché, la Normandie joua un rôle clé dans l'histoire : conquête de l'Angleterre en 1066 (tapisserie de Bayeux) et débarquement allié du 6 juin 1944. Région des impressionnistes (Monet à Giverny).",
    points: "Mont Saint-Michel · Plages du Débarquement · Étretat · Giverny · Honfleur · Rouen",
    economie: "Agroalimentaire (camembert, cidre), automobile, énergie et tourisme."
  },
  "nouvelle-aquitaine": {
    name: "Nouvelle-Aquitaine",
    type: "metro",
    icon: "🏄",
    chef: "Bordeaux",
    color: "#9cc06a",
    population: "6 075 949",
    superficie: "84 036 km²",
    departements: 12,
    densite: "72 hab/km²",
    histoire: "Plus grande région métropolitaine, fusion de l'Aquitaine, du Limousin et du Poitou-Charentes. Riche d'un patrimoine préhistorique (grottes de Lascaux), viticole (Bordeaux) et balnéaire (côte atlantique, Biarritz).",
    points: "Bordeaux · Dune du Pilat · Lascaux · Biarritz · La Rochelle · Vignobles bordelais",
    economie: "Viticulture, aéronautique, agriculture, surf et tourisme balnéaire."
  },
  "occitanie": {
    name: "Occitanie",
    type: "metro",
    icon: "☀️",
    chef: "Toulouse",
    color: "#f0975a",
    population: "5 999 982",
    superficie: "72 724 km²",
    departements: 13,
    densite: "82 hab/km²",
    histoire: "Fusion de Languedoc-Roussillon et Midi-Pyrénées, héritière de la culture occitane et cathare. Toulouse, la « ville rose », est la capitale européenne de l'aéronautique et du spatial (Airbus).",
    points: "Cité de Carcassonne · Pont du Gard · Toulouse · Canal du Midi · Pyrénées · Lourdes",
    economie: "Aéronautique, spatial, viticulture, agriculture et tourisme."
  },
  "pays-de-la-loire": {
    name: "Pays de la Loire",
    type: "metro",
    icon: "🚢",
    chef: "Nantes",
    color: "#f0975a",
    population: "3 832 120",
    superficie: "32 082 km²",
    departements: 5,
    densite: "119 hab/km²",
    histoire: "Région de l'ouest tournée vers l'Atlantique, mêlant patrimoine ducal (Nantes, ancienne capitale bretonne) et stations balnéaires. Les Machines de l'île à Nantes incarnent sa créativité.",
    points: "Château des ducs de Bretagne · Machines de l'île · Puy du Fou · Le Mans · La Baule",
    economie: "Construction navale, agroalimentaire, aéronautique et tourisme."
  },
  "provence-alpes-cote-dazur": {
    name: "Provence-Alpes-Côte d'Azur",
    type: "metro",
    icon: "🌊",
    chef: "Marseille",
    color: "#f5d020",
    population: "5 098 666",
    superficie: "31 400 km²",
    departements: 6,
    densite: "162 hab/km²",
    histoire: "Région du soleil entre Alpes et Méditerranée, terre des peintres (Cézanne, Van Gogh) et du cinéma (Cannes). Marseille, fondée par les Grecs il y a 2 600 ans, est la plus ancienne ville de France.",
    points: "Marseille (Vieux-Port, Calanques) · Nice · Cannes · Gorges du Verdon · Avignon · Saint-Tropez",
    economie: "Tourisme, parfumerie (Grasse), microélectronique, agriculture et activités portuaires."
  }
};
